version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
      # Variables to connect to our Postgres server
      CAR_API_DB_NAME: postgres
      CAR_API_DB_USER: postgres
      CAR_API_DB_PASSWORD: postgres
      # Hostname of our Postgres container
      CAR_API_DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
