# Generated by Django 2.1.5 on 2019-04-01 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=10)),
                ('passangers', models.IntegerField()),
                ('production_year', models.IntegerField()),
                ('producent', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('motor_type', models.CharField(max_length=20)),
            ],
        ),
    ]
