# Generated by Django 2.1.5 on 2019-04-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='motor_type',
            field=models.BooleanField(),
        ),
    ]
