# Generated by Django 2.1.5 on 2019-04-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20190403_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='motor_type',
            new_name='electric_or_hybrid',
        ),
    ]
